### ISSUE TITLE
Have a timeout whilst waiting for nodes to reboot

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/container-linux-update-operator#91] opened 2017-06-22 14:28 UTC
Right now the operator [waits](https://github.com/coreos/container-linux-update-operator/blob/793fe40c8b2f29590c1d28f682785a399fce8969/pkg/operator/operator.go#L243) for the node to restart so that the agent can remove the `stillRebootingSelector`. One issue we're seeing is that something goes wrong on the node, and it gets stuck in the rebooting stage (we couldn't even ssh in). The result is that the controller is waiting indefinitely for the node to reboot, whereas a timeout might be better.

An even better option would be that, once this timeout is reached, the operator evicts all pods from this node allowing the cluster to handle the temporary node loss. A user would then respawn the node.

**Comment by dghubble** [comment] 2017-06-26 18:22
Can you file the Container Linux upgrade failure (i.e. never came back and `couldn't even ssh`) on [coreos/bugs](https://github.com/coreos/bugs).

Reboots are supposed to be coordinated, one at a time, so that a node upgrades successfully before the next node is allowed to reboot. Releasing the lock after a timeout would allow a bad upgrade to propagate across a cluster. If a node upgrade fails, that merits manual inspection and bug filing.

For those who wish to continue anyway, manually releasing the lock would be one option. Allowing a higher number of reboots to occur at once (e.g. 1 -> 3) would be another way, though you'd wanna weight the tradeoffs.

**Comment by dghubble** [comment] 2017-08-15 18:53
Timing out and continuing to upgrade more nodes in the cluster is inherently dangerous. If the failure is in Container Linux itself, it warrants manual intervention and a bug report so we can fix ASAP.

If the failure is related to your workloads, with the new before-reboot and after-reboot feature in v0.3.0 we now allow you to write pods that do custom checks to provide additional safety guarantees (e.g. important app X is running) before continuing to upgrade the next node. https://github.com/coreos/container-linux-update-operator/blob/master/doc/before-after-reboot-checks.md

Do you still have a need for relaxing these safety gates? I don't think a timeout would be suitable.

**Comment by dghubble** [comment] 2017-10-09 21:46
Followup on this? Otherwise I'd like to close this as "working as intended".

If a node upgrades and doesn't come back, we don't want to keep rolling out upgrades to other nodes.

**Comment by jamiehannaford** [comment] 2017-10-10 08:33
I understand what you mean about timeouts being inherently dangerous, but I think it'd still be useful for the reboot algorithm to handle failure more gracefully. Right now, it seems that the operator will hang requiring manual intervention (I haven't checked new functionality to see whether this is still the case), but it'd be great if it could initiate or defer to some kind of disaster recovery policy. 

For example, if a node is unresponsive post-reboot, either drain or delete it, then if possible spin another node up. This should probably be handled by a custom controller or operator, and would be triggered similarly to the pre/post hooks you've recently added. Would the "after" hook be triggered after a failed reboot? If so, would the pod know whether the reboot was unsuccessful? If not, would it be possible to add a new event for errors?

**Closed** 2018-02-26 13:09 UTC
