### ISSUE TITLE
update-agent will always exit when API watches conclude

### ISSUE THREAD

**Issue by colhom** [coreos/container-linux-update-operator#79] opened 2017-06-07 19:13 UTC
As of now, update-agent process will exit when the `watch.Until` invocations conclude, regardless of error cases. According to an [issue comment](https://github.com/kubernetes/kubernetes/issues/42552#issuecomment-284272947), this is inevitable in all cases.

> All watches are terminated by the server after a certain point. No retries are done today. 

From a monitoring/visibility standpoint- it's fairly alarming to have a control plane component that insists on spuriously restarting in a healthy cluster, even if exit status is 0.

**Comment by crawford** [comment] 2017-06-07 20:06
This is a duplicate of https://github.com/coreos/container-linux-update-operator/issues/75. Is there something I'm missing?

**Comment by colhom** [comment] 2017-06-07 20:37
> Is there something I'm missing?

Yes.

#75 refers to the case where `watch.Until` returns a specific error. This refers to the general case the `watch.Until` returns with or without error. For instance, in the case `watch.Until` returns no error and there is no reboot, the `update-agent` process will exit with status 0. We would like it to attempt stay running in this case.

**Comment by crawford** [comment] 2017-06-08 19:24
Fine. We can keep both issues and resolve them at the same time.

**Comment by euank** [comment] 2017-06-22 22:10
Fixed in #89

**Closed by euank** 2017-06-22 22:10 UTC
